version: 0.1

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Running lint checks..."
      - npm run lint

  build:
    commands:
      - echo "Building the application..."
      - npm run build

artifacts:
  base-directory: .next/static
  files:
    - '**/*'

cache:
  paths:
    - 'node_modules/**/*'
